### PR TITLE
Changes to the structure of the library

### PR DESCRIPTION
**Pull request by pacs27**
In this commit I propose a new library structure. The inner workings however remain the same. The changes made include the following:

* New tests
* Automation of github workflows
* Automated AOT file compilation
* Small bugs fixed
* simulation dates formatting and weather data formatting checked
* Fixed some linting bugs
* In the core file, private variables and methods are distinguished from public ones.
* Other minor changes

The library produces major changes that are incompatible with older versions. Therefore it would be advisable to update the documentation before making a new realease. These changes are:

* The importing of classes is now different.
* The names of classes and variables now follow the camel_case format.
* the aquacrop class now returns the following 5 public methods:

```python
run_model(): Run the model.

get_simulation_results(): Get the final results.

get_water_storage(): Get the water storage values.

get_water_flux(): Get the water flux values.

get_crop_growth(): Get the crop growth values.

get_additional_information(): Get additional information of the model.

```

Here is an example of how it works:

```python

from aquacrop.core import AquaCropModel
from aquacrop.entities.soil import Soil
from aquacrop.entities.crop import  Crop
from aquacrop.entities.inititalWaterContent import InitialWaterContent
from aquacrop.utils.prepare_weather import prepare_weather
from aquacrop.utils.data import get_filepath

weather_file_path = get_filepath('tunis_climate.txt')

modelOs = AquaCropModel(
            sim_start_time=f"{1979}/10/01",
            sim_end_time=f"{1985}/05/30",
            weather_df=prepare_weather(weather_file_path),
            soil=Soil(soil_type='SandyLoam'),
            crop=Crop('Wheat', planting_date='10/01'),
            initial_water_content=InitialWaterContent(value=['FC']),
        )

model_os.run_model(till_termination=True)
model_results = model_os.get_simulation_results().head()
print(model_results)
```

### CODE REVIEW

**Comment by thomasdkelly** [comment]
Hi @pacs27 thanks again for all your efforts putting this together, will start adding in the docs files, tutorial notebooks (and updating them to the new structure), etc.

**Comment by thomasdkelly** [comment]
Since the compilation process takes a little while (40 secs on my pc) i think it would be good to have a little progress bar so people know nothing has frozen or broke while they are waiting

**Comment by pacs27** [comment]
> Since the compilation process takes a little while (40 secs on my pc) i think it would be good to have a little progress bar so people know nothing has frozen or broke while they are waiting

This is a very good feature!

**Comment by pacs27** [comment]
I have been looking at error #48  As you said it is a good idea to round off the decimals in all if statments. I'm very busy this week but I'll do those modifications when I can.

**Comment by thomasdkelly** [comment]
Yeah Ill get some advice from Tim Foster about the precision of the rounding as some varibales may need more precision and some less (e.g., curve number CN gets rounded to int).

I was working on your PR yesterday, have updated the comparison notebook and all the outputs are the same as before your changes so thats good. Also found a bug inside `rainfall_partition` similar to this GW issue where we were missing out one of the compartments. Will add the changes to the PR.

When adding the mkdocs files I find that the docstrings for the functions may need to change format slightly format to fit what mkdocs is looking for

**Comment by pacs27** [comment]
I agree. It is very important to take into account the precision of the variables.

What format should the dockstrings follow?

**Comment by thomasdkelly** [comment]
yes definitely i like that a lot. 

Can it be done by adding
```
from aquacrop.core import AquaCropModel
from aquacrop.entities.soil import Soil
from aquacrop.entities.crop import  Crop
from aquacrop.entities.inititalWaterContent import InitialWaterContent
```
to the aquacrop.__init__.py ?

**Comment by pacs27** [comment]
> yes definitely i like that a lot.
> 
> Can it be done by adding
> 
> ```
> from aquacrop.core import AquaCropModel
> from aquacrop.entities.soil import Soil
> from aquacrop.entities.crop import  Crop
> from aquacrop.entities.inititalWaterContent import InitialWaterContent
> ```
> 
> to the `aquacrop.__init__.py `?

yes, that's the way to do it

**Comment by thomasdkelly** [comment]
I though i had fixed the recursive compilation issue but apparently not. Are you able to cancel the github action as it wont let me on your fork.

**Comment by thomasdkelly** [comment]
To fix this merge conflict i think ill have to create a settings.ini file temporarily then delete it afterwards

**Comment by thomasdkelly** [comment]
okay nearly ready to merge, all tests pass (except deploying the docs which should work when merged)

**Comment by thomasdkelly** [comment]
Think the final thing to fix before merging is the docs

**Comment by pacs27** [comment]
I'm finishing a commit where I add typing to the core file. It is very useful to see possible errors that are not visible.

**Comment by thomasdkelly** [comment]
Have updated the core doc strings in line with mkdocs. Am pretty happy with how the docs look so will probably merge soon and update the rest from there.

**Comment by pacs27** [comment]
I thought it might be more convenient to pull out the prepare_weather and
get_filepath functions out of the main module and call them through the utils folder. These functions don't really have anything to do with the model although they can be useful.

It would look like this:
```python
from aquacrop import AquaCropModel, Soil, Crop, InitialWaterContent, IrrigationManagement
from aquacrop.utils import prepare_weather
from aquacrop.utils import get_filepath
```

What do you think of this?

**Comment by thomasdkelly** [comment]
I thought about changing the docstring formats first but will put that in a seperate pull request.

Just going to change colab links to binder links as colab only supports python 3.6, 3.7.

Then will merge

**Comment by pacs27** [comment]
> I thought about changing the docstring formats first but will put that in a seperate pull request.
> 
> Going to go ahead and merge now. Thanks a lot for all your help @pacs27 !
> 
> Then will fix new links etc. Also need to change colab links to binder links as colab only supports python 3.6, 3.7.

Great. It's been a pleasure helping you.

**Pull request merged**
